baseURL: 'https://jonathanbucaro.com/'
languageCode: en-us
title: Jonathan Búcaro
theme: hilton
pagination:
    pagerSize: 6
build:
    writeStats: true
    useResourceCacheWhen: fallback
    processing:
        css:
            minify: true
            postcss: true
        js:
            minify: true
        html:
            minify: true
        sass:
            enable: true
            outputStyle: compressed
outputFormats:
    RobotsTXT:
        mediaType: text/plain
        baseName: robots
        isPlainText: true
        notAlternative: true

outputs:
    home:
        - HTML
        - RSS
        - RobotsTXT
