baseURL: 'https://jonathanbucaro.com/'
defaultContentLanguage: es
languageCode: es-gt
title: Sitio de Jonathan Búcaro
theme: hilton
pagination:
  pagerSize: 6
build:
  writeStats: true
  processing:
    css:
      minify: true
      postcss: true
    sass:
      enable: true
      outputStyle: compressed
