baseURL: 'https://jonathanbucaro.com/'

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
    en:
        locale: en-US
        label: English
        direction: ltr
        weight: 1
        title: Jonathan Búcaro
        params:
            lang_flag: '🇺🇸'
            lang_label: 'EN'

    es:
        locale: es-GT
        label: Español
        direction: ltr
        weight: 2
        title: Jonathan Búcaro
        params:
            lang_flag: '🇬🇹'
            lang_label: 'ES'
pagination:
    pagerSize: 6
build:
    writeStats: true
    useResourceCacheWhen: fallback
    processing:
        css:
            minify: true
            postcss: true
        js:
            minify: true
        html:
            minify: true
        sass:
            enable: true
            outputStyle: compressed
outputFormats:
    RobotsTXT:
        mediaType: text/plain
        baseName: robots
        isPlainText: true
        notAlternative: true

outputs:
    home:
        - HTML
        - RSS
        - RobotsTXT
