main:
    - identifier: home
      name: Inicio
      url: /
      weight: 10
    # - identifier: projects
    #   name: Proyectos
    #   url: /proyectos/
    #   weight: 20
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
      hasChildren: true
    - identifier: pages
      name: Páginas
      weight: 40
    - parent: pages
      name: Acerca de
      url: /acerca-de/
      weight: 10
    - parent: pages
      name: Lista Imposible
      url: /mi-lista-imposible/
      weight: 20
    # - parent: pages
    #   name: Contacto
    #   url: /contact/
    #   weight: 20
footer:
    - identifier: home
      name: Inicio
      url: /
      weight: 10
    # - identifier: projects
    #   name: Proyectos
    #   url: /proyectos/
    #   weight: 20
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 30
    - identifier: about
      name: Acerca de
      url: /acerca-de/
      weight: 40
    - identifier: impossible
      name: Lista Imposible
      url: /mi-lista-imposible/
      weight: 50
    # - identifier: contact
    #   name: Contacto
    #   url: /contact/
    #   weight: 50
