main:
    - identifier: home
      name: Inicio
      url: /es/
      weight: 10
    - identifier: about
      name: Acerca de
      url: /es/about/
      weight: 30
    - identifier: pages
      name: Páginas
      weight: 40
      hasChildren: true
    - identifier: blog
      parent: pages
      name: Blog
      url: /es/blog/
      weight: 10

footer:
    - identifier: home
      name: Inicio
      url: /es/
      weight: 10
    - identifier: about
      name: Acerca de
      url: /es/about/
      weight: 30
    - identifier: blog
      name: Blog
      url: /es/blog/
      weight: 40
