main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: pages
      name: Pages
      weight: 40
      hasChildren: true
    - identifier: projects
      name: Projects
      parent: pages
      url: /projects/
      weight: 10
    - identifier: blog
      parent: pages
      name: Blog
      url: /blog/
      weight: 20

footer:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 30
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 40
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 50
