logo: '/images/logo.webp'
description: ''
color_scheme: auto
author:
    author__name: Jonathan Búcaro
    author__avatar: '/images/perfil.webp'
social:
    - icon: logo-linkedin
      name: LinkedIn
      link: 'https://www.linkedin.com/in/jonathanbucaro/'
    - icon: logo-github
      name: Github
      link: 'https://github.com/jebucaro'
    - icon: logo-x
      name: X
      link: 'https://x.com/jebucaro'
    - icon: logo-instagram
      name: Instagram
      link: 'https://instagram.com/jebucaro'
hero:
    enable: true
    hero__image: '/images/perfil.webp'
mailchimp:
    enable: false
    mailchimp__identifier: >-
        frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text: 'Correo electrónico...'
    mailchimp__button__text: Recibir actualizaciones
projects:
    enable: true
testimonials:
    enable: true
testimonial_item:
    - name: Aspen Carder
      image: 'https://via.placeholder.com/200x200'
      designation: Lettering Artist
      link: 'https://twitter.com/'
      content: >-
          Keeping your eye on the ball while performing a deep dive on the
          start-up mentality to derive convergence on cross-platform integration
    - name: Lydia Siphron
      image: 'https://via.placeholder.com/200x200'
      designation: Designer
      link: 'https://facebook.com/'
      content: >-
          Keeping your eye on the ball while performing a deep dive on the
          start-up mentality to derive convergence on cross-platform integration
    - name: Craig Vaccaro
      image: 'https://via.placeholder.com/200x200'
      designation: Web developer
      link: 'https://twitter.com/'
      content: >-
          Keeping your eye on the ball while performing a deep dive on the
          start-up mentality to derive convergence on cross-platform integration
    - name: Anika Calzoni
      image: 'https://via.placeholder.com/200x200'
      designation: Lettering Artist
      link: 'https://facebook.com/'
      content: >-
          Keeping your eye on the ball while performing a deep dive on the
          start-up mentality to derive convergence on cross-platform integration
    - name: Marcus Botosh
      image: 'https://via.placeholder.com/200x200'
      designation: Full Stack Designer
      link: 'https://twitter.com/'
      content: >-
          Keeping your eye on the ball while performing a deep dive on the
          start-up mentality to derive convergence on cross-platform integration
blog:
    enable: true
    blog__title: Publicaciones Recientes
    blog__description: ''
gallery:
    enable: false
gallery_image:
    - image_alt: Rest
      image_url: 'https://via.placeholder.com/800x800'
    - image_alt: Lifestyle
      image_url: 'https://via.placeholder.com/800x800'
    - image_alt: Hobby
      image_url: 'https://via.placeholder.com/800x800'
    - image_alt: Notes
      image_url: 'https://via.placeholder.com/800x800'
contact:
    contact__email: hola@jonathanbucaro.com
disqus:
    enable: false
    disqusShortname: anvodstudio-demo
logos:
    enable: true
    logos__title: 'Mi experiencia profesional incluye colaboraciones con las siguientes compañías:'
logo_item:
    - name: 'Banco G&T Continental'
      link: 'https://gtc.com.gt/'
      image: '/images/gyt-logo.webp'
    - name: 'Cognits'
      link: 'https://cognits.co/'
      image: '/images/cognits-logo.webp'
formats:
  date:
    long: "January 2, 2006"
    short: "Jan 2, 2006"
    iso: "2006-01-02"
