# Spanish localized parameters
description: 'Jonathan Búcaro 🤓 — Apasionado por crear software con impacto. Escribo sobre C#, Python, IA Generativa, herramientas CLI y experiencias en el mundo del desarrollo.'
author:
    author__bio: >-
        Ingeniero en Sistemas y Planeswalker. Escribo sobre mi viaje en la tecnología, compartiendo experiencias e ideas que han impulsado mi desarrollo profesional.

blog:
    blog__title: Publicaciones Recientes
    blog__description: ''

logos:
    logos__title: 'Mi experiencia profesional incluye colaboraciones con las siguientes empresas:'
