# English localized parameters
description: 'Jonathan Búcaro 🤓 — Passionate about crafting high-quality tech solutions. I write about C#, Python, AI, CLI tools, and lessons learned in software development.'
author:
    author__bio: >-
        Systems Engineer and Planeswalker. I write about my journey in technology, sharing experiences and insights that have driven my professional development.

blog:
    blog__title: Recent Posts
    blog__description: ''

logos:
    logos__title: 'My professional experience includes collaborations with the following companies:'
