# English localized parameters
description: 'Jonathan Búcaro 🤓. I like building software and writing about what I learn along the way, C#, Python, AI, and CLI tools included.'
author:
    author__bio: >-
        Systems Engineer and Planeswalker. I write about my journey in technology, sharing experiences and insights that have driven my professional development.

blog:
    blog__title: Recent Posts
    blog__description: ''

logos:
    logos__title: 'My professional experience includes collaborations with the following companies:'
