# Production environment configuration
baseURL: 'https://jonathanbucaro.com/'
buildDrafts: false
buildFuture: false
buildExpired: false

params:
    env: production
    debug: false

# Production-specific build optimizations
minifyOutput: true
canonifyURLs: false
relativeURLs: true
